"""Edit a course's prompt cards through one Markdown file.

  python _prompts/prompts.py export                          # chapters -> _prompts/prompts.md
  python _prompts/prompts.py apply                           # _prompts/prompts.md -> chapters
  python _prompts/prompts.py apply _prompts/hyperframes.md   # apply only the prompts in another file

The `### title` line is the key: it must match a card's data-title in the chapter HTML.
Appendix A (prompt collection page) is generated by the app, so it updates by itself.
"""
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
COURSE = ROOT / "content" / "courses" / "interactive-site"
MD = ROOT / "_prompts" / "prompts.md"
CARD = re.compile(r'(<figure class="prompt" data-title="([^"]+)">.*?<pre>)(.*?)(</pre>)', re.S)
BANNED = {"\u00b7": ", ", "\u2014": "-", "\u2013": "-"}  # middle dot, em dash, en dash


def fragments():
    """(path, 'NN title') for each chapter file in course order."""
    for cid in json.loads((COURSE / "course.json").read_text(encoding="utf-8"))["chapters"]:
        f = COURSE / f"{cid}.html"
        if not f.exists():
            continue  # generated pages (prompts) have no file
        s = f.read_text(encoding="utf-8")
        num = re.search(r'<span class="chapter-num">([^<]+)</span>', s).group(1)
        title = re.sub(r"<[^>]+>", "", re.search(r"<h2>(.*?)</h2>", s, re.S).group(1)).strip()
        yield f, f"{num} {title}"


def export():
    out = [
        "# 프롬프트 모음 (편집용)",
        "",
        "- `###` 줄은 프롬프트 이름입니다. 바꾸지 마세요. 이 이름으로 사이트의 자리를 찾습니다.",
        "- 고칠 곳은 ```text 와 ``` 사이뿐입니다. 줄바꿈은 그대로 사이트에 나옵니다.",
        "- [대괄호]는 수강생이 자기 내용으로 바꿔 넣는 자리입니다.",
        "- 가운뎃점, em dash, en dash는 반영할 때 자동으로 쉼표와 하이픈으로 바뀝니다.",
        "",
    ]
    n = 0
    for f, title in fragments():
        cards = CARD.findall(f.read_text(encoding="utf-8"))
        if not cards:
            continue
        out += [f"## {title}", ""]
        for _, name, pre, _ in cards:
            out += [f"### {name}", "```text", html.unescape(pre).strip("\n"), "```", ""]
            n += 1
    MD.write_text("\n".join(out), encoding="utf-8")
    print(f"exported {n} prompts -> {MD}")


def apply(src=MD):
    edits = dict(re.findall(r"^### (.+?)\n```text\n(.*?)\n```", pathlib.Path(src).read_text(encoding="utf-8"), re.S | re.M))
    fixed = 0
    for k, v in edits.items():
        for bad, good in BANNED.items():
            fixed += v.count(bad)
            v = v.replace(bad, good)
        edits[k] = v
    seen, changed = set(), 0

    def swap(m):
        nonlocal changed
        name = m.group(2)
        if name not in edits:
            return m.group(0)
        seen.add(name)
        new = html.escape(edits[name], quote=False)
        if new == m.group(3):
            return m.group(0)
        changed += 1
        return m.group(1) + new + m.group(4)

    for f, _ in fragments():
        s = f.read_text(encoding="utf-8")
        t = CARD.sub(swap, s)
        if t != s:
            f.write_text(t, encoding="utf-8")
    print(f"changed {changed} cards, banned chars fixed {fixed}")
    unknown = sorted(set(edits) - seen)
    if unknown:
        print("titles not found (ignored):", *unknown, sep="\n  ")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "export"
    if cmd == "apply":
        apply(*sys.argv[2:3])
    else:
        export()
